### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mani-rai** [jmriebold/BoilerPy3#4]
I am trying to try boilerpy3 with simple warc file. However getting the following error:

> Error parsing HTML
Traceback (most recent call last):
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/extractors.py", line 81, in parse_doc
    bp_parser.feed(input_str)
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/parser.py", line 652, in feed
    self.end_document()
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/parser.py", line 459, in end_document
    self.flush_block()
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/parser.py", line 534, in flush_block
    if self.last_start_tag.lower() == "title":
AttributeError: 'NoneType' object has no attribute 'lower'

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/extractors.py", line 87, in parse_doc
    bp_parser.feed(input_str)
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/parser.py", line 652, in feed
    self.end_document()
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/parser.py", line 459, in end_document
    self.flush_block()
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/parser.py", line 534, in flush_block
    if self.last_start_tag.lower() == "title":
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/home/mani/Workspace/Researches/Thesis/nparacrawl/npc-miner/main.py", line 23, in <module>
    app.create_db()
  File "/home/mani/Workspace/Researches/Thesis/nparacrawl/npc-miner/main.py", line 19, in create_db
    print(text_extractor.get_content(text))
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/extractors.py", line 33, in get_content
    return self.get_doc(text).content
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/extractors.py", line 49, in get_doc
    self.filter.process(doc)
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/filters.py", line 98, in process
    is_updated |= filtr.process(doc)
  File "/home/mani/.python-venvs/research1/lib/python3.8/site-packages/boilerpy3/filters.py", line 859, in process
    for tb in doc.text_blocks:
AttributeError: 'NoneType' object has no attribute 'text_blocks'
Example Domain
This domain is established to be used for illustrative examples in documents. You may use this
    domain in examples without prior coordination or asking for permission.

I was using [this](https://github.com/webrecorder/pywb/blob/master/sample_archive/warcs/dupes.warc.gz) this warc file for testing. It successfully extracts text but leaves with error message. For complex webpages, I am not getting any output except error message. I have tried with python 3.9 and 3.8. Anybody aware of this?

**Comment by jmriebold** [comment]
Hey @mani-rai, this error indicates that no text was extracted from the page. An `AttributeError` is not very helpful here though, so I'll see about handling it and reraising something more useful.

**Comment by jmriebold** [comment]
The HTML from the example file you sent appears to work fine, by the way. If you can attach some HTML that triggers exceptions that'd make it easier to verify the changes.

**Comment by mani-rai** [comment]
Thanks @jmriebold. Forgot to respond to the issue. Yes, the input was empty.
