### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by sufwankhalid** [jmriebold/BoilerPy3#9]
When running the code provided, an error occurred while trying to parse HTML. The error message indicates that there was an issue with the boilerpy3 package, specifically the parse_doc function. The error occurred when trying to pop an element from an empty list, indicating that the parser encountered an unexpected condition during parsing. This caused the parser to fail, and prevented the program from completing successfully.

sample input html is attached
[fail1.html.zip](https://github.com/jmriebold/BoilerPy3/files/11472298/fail1.html.zip)

To replicate the issue, the following code was used:

```
from boilerpy3 import extractors
extractor = extractors.ArticleSentencesExtractor()
doc = extractor.get_doc(x)
page_contents = doc.content
```

```
Error parsing HTML
Traceback (most recent call last):
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/extractors.py", line 108, in parse_doc
    bp_parser.feed(input_str)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 657, in feed
    HTMLParser.feed(self, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 667, in handle_endtag
    self.end_element(tag)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 495, in end_element
    self.label_stacks.pop()
IndexError: pop from empty list
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/extractors.py", line 114, in parse_doc
    bp_parser.feed(input_str)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 657, in feed
    HTMLParser.feed(self, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 667, in handle_endtag
    self.end_element(tag)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 495, in end_element
    self.label_stacks.pop()
IndexError: pop from empty list
Traceback (most recent call last):
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/extractors.py", line 108, in parse_doc
    bp_parser.feed(input_str)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 657, in feed
    HTMLParser.feed(self, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 667, in handle_endtag
    self.end_element(tag)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 495, in end_element
    self.label_stacks.pop()
IndexError: pop from empty list
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/extractors.py", line 114, in parse_doc
    bp_parser.feed(input_str)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 657, in feed
    HTMLParser.feed(self, data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 667, in handle_endtag
    self.end_element(tag)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/parser.py", line 495, in end_element
    self.label_stacks.pop()
IndexError: pop from empty list
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1578, in <module>
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/extractors.py", line 63, in get_doc
    doc = self.parse_doc(text)
  File "/Users/mac/Desktop/django/envs/seotool/lib/python3.9/site-packages/boilerpy3/extractors.py", line 118, in parse_doc
    raise HTMLExtractionError from ex
boilerpy3.exceptions.HTMLExtractionError
```

**Comment by jmriebold** [comment]
Hi @sufwankhalid, that most likely means there's something wrong with the HTML (e.g. unclosed tag) resulting in BoilerPy3 hitting an error. You can set `raise_on_failure=False` in your `Extractor` to workaround this, see the [note](https://github.com/jmriebold/BoilerPy3#extractors) in the README.
